// Autogenerated by tools/generate_initrd.py - DO NOT EDIT MANUALLY
static PROGRAMS: &[(&str, &[u8])] = &[
    ("forktest", include_bytes!("../../build/forktest.elf")),
    ("01_hello", include_bytes!("../../build/01_hello.elf")),
    ("02_variabel", include_bytes!("../../build/02_variabel.elf")),
    ("variabel", include_bytes!("../../build/02_variabel.elf")),
    ("03_aritmatika", include_bytes!("../../build/03_aritmatika.elf")),
    ("aritmatika", include_bytes!("../../build/03_aritmatika.elf")),
    ("04_if_else", include_bytes!("../../build/04_if_else.elf")),
    ("if_else", include_bytes!("../../build/04_if_else.elf")),
    ("05_while", include_bytes!("../../build/05_while.elf")),
    ("while", include_bytes!("../../build/05_while.elf")),
    ("06_fungsi", include_bytes!("../../build/06_fungsi.elf")),
    ("fungsi", include_bytes!("../../build/06_fungsi.elf")),
    ("07_syscall", include_bytes!("../../build/07_syscall.elf")),
    ("syscall", include_bytes!("../../build/07_syscall.elf")),
    ("08_perkenalan", include_bytes!("../../build/08_perkenalan.elf")),
    ("perkenalan", include_bytes!("../../build/08_perkenalan.elf")),
    ("hello", include_bytes!("../../build/hello.elf")),
];

pub fn init() {
    for (name, image) in PROGRAMS {
        let path = alloc::format!("/bin/{}", name);
        match crate::vfs::write_file(&path, image) {
            Ok(()) => crate::logln!(
                "[Initrd] Registered {} ({} bytes).",
                path,
                image.len()
            ),
            Err(err) => crate::logln!("[Initrd] Failed to register {}: {}", path, err),
        }
    }
}
