#!/usr/bin/env python3
import os
import glob
import subprocess
import sys

# Paths relative to NyxaraOS root
NYXARA_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD_DIR = os.path.join(NYXARA_ROOT, "build")
INITRD_RS = os.path.join(NYXARA_ROOT, "rust", "src", "initrd.rs")
NYXC_MANIFEST = os.path.join(NYXARA_ROOT, "..", "NyxC", "Cargo.toml")
NYXC_BIN = os.path.join(NYXARA_ROOT, "..", "NyxC", "target", "debug", "nyxc")

os.makedirs(BUILD_DIR, exist_ok=True)

# 1. Compile NyxC if not built
if not os.path.exists(NYXC_BIN):
    print("[tools] Building NyxC compiler...")
    res = subprocess.run(["cargo", "build", "--manifest-path", NYXC_MANIFEST], check=True)

# 2. Discover all .nyx files in ../NyxC and ../NyxC/Learning-NyxC
nyx_search_patterns = [
    os.path.join(NYXARA_ROOT, "..", "NyxC", "*.nyx"),
    os.path.join(NYXARA_ROOT, "..", "NyxC", "Learning-NyxC", "*.nyx"),
]

nyx_files = []
for pattern in nyx_search_patterns:
    nyx_files.extend(glob.glob(pattern))

nyx_files = sorted(set(nyx_files))

programs = []

# Keep forktest if available
forktest_elf = os.path.join(BUILD_DIR, "forktest.elf")
if os.path.exists(forktest_elf):
    programs.append(("forktest", "../../build/forktest.elf"))

# 3. Compile each .nyx file into build/<progname>.elf
for nyx_path in nyx_files:
    fname = os.path.basename(nyx_path)
    # Format command name: e.g. 01_hello.nyx -> 01_hello and/or hello
    raw_name = os.path.splitext(fname)[0]
    elf_filename = f"{raw_name}.elf"
    out_elf_path = os.path.join(BUILD_DIR, elf_filename)

    # Check if needs rebuild
    needs_rebuild = True
    if os.path.exists(out_elf_path):
        if os.path.getmtime(out_elf_path) >= os.path.getmtime(nyx_path) and os.path.getmtime(out_elf_path) >= os.path.getmtime(NYXC_BIN):
            needs_rebuild = False

    if needs_rebuild:
        print(f"[NyxC] Compiling {nyx_path} -> {out_elf_path}")
        cmd = [NYXC_BIN, "build", nyx_path, "-o", out_elf_path]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print(f"Error compiling {nyx_path}:\n{res.stderr or res.stdout}", file=sys.stderr)
            sys.exit(1)

    programs.append((raw_name, f"../../build/{elf_filename}"))
    # Also register short aliases without prefix number, e.g. '01_hello' -> also alias 'hello'
    # but only if not conflicting or if it is hello
    if "_" in raw_name and raw_name[:2].isdigit():
        alias = raw_name.split("_", 1)[1]
        if alias != "hello" and not any(p[0] == alias for p in programs):
            programs.append((alias, f"../../build/{elf_filename}"))

# 4. Generate rust/src/initrd.rs
lines = [
    "// Autogenerated by tools/generate_initrd.py - DO NOT EDIT MANUALLY",
    "static PROGRAMS: &[(&str, &[u8])] = &[",
]

for name, rel_path in programs:
    lines.append(f'    ("{name}", include_bytes!("{rel_path}")),')

lines.append("];")
lines.append("")
lines.append("pub fn init() {")
lines.append("    for (name, image) in PROGRAMS {")
lines.append('        let path = alloc::format!("/bin/{}", name);')
lines.append("        match crate::vfs::write_file(&path, image) {")
lines.append("            Ok(()) => crate::logln!(")
lines.append('                "[Initrd] Registered {} ({} bytes).",')
lines.append("                path,")
lines.append("                image.len()")
lines.append("            ),")
lines.append('            Err(err) => crate::logln!("[Initrd] Failed to register {}: {}", path, err),')
lines.append("        }")
lines.append("    }")
lines.append("}")
lines.append("")

content = "\n".join(lines)

# Write only if changed
old_content = ""
if os.path.exists(INITRD_RS):
    with open(INITRD_RS, "r") as f:
        old_content = f.read()

if content != old_content:
    with open(INITRD_RS, "w") as f:
        f.write(content)
    print(f"[tools] Updated {INITRD_RS} with {len(programs)} program entries.")
